const nadadoresAlmafuerte = [{
        "apellido": 'Molina',
        "nombre": 'Lucia',
        "club": 'ASOCIACIÓN INDEPENDIENTE DOLORES',
        'id': '',
        "documento": 44975742,
        "nivel": 'AFICIONADO',
        "fecha": '37844',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },

    {
        "apellido": 'Rodriguez',
        "nombre": 'Juan Pablo',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 28042181,
        "nivel": 'AFICIONADO',
        "fecha": '29289',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Mena',
        "nombre": 'Facundo',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 33666329,
        "nivel": 'NACIONAL',
        "fecha": '32311',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'MASTER C',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Ruiz Luques',
        "nombre": 'Victoria',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 35581049,
        "nivel": 'NACIONAL',
        "fecha": '33377',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'MASTER B',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Wayar',
        "nombre": 'Waldo',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 17000565,
        "nivel": 'AFICIONADO',
        "fecha": '23574',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 5',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Mestre',
        "nombre": 'Ivone',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 16926495,
        "nivel": 'AFICIONADO',
        "fecha": '23866',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Fagotti',
        "nombre": 'Agustin',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 32907156,
        "nivel": 'AFICIONADO',
        "fecha": '31863',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Castelli',
        "nombre": 'Carla',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 40210742,
        "nivel": 'AFICIONADO',
        "fecha": '35606',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Ayrolo',
        "nombre": 'Julieta',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 25436454,
        "nivel": 'NACIONAL',
        "fecha": '28026',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'MASTER E',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Hrenadiez',
        "nombre": 'Mauro',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 31749932,
        "nivel": 'AFICIONADO',
        "fecha": '31272',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Centineo',
        "nombre": 'Gustavo',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 20621372,
        "nivel": 'AFICIONADO',
        "fecha": '25230',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Schneider',
        "nombre": 'Julio',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 13682878,
        "nivel": 'AFICIONADO',
        "fecha": '21786',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 5',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Higa',
        "nombre": 'Veronica',
        "club": 'ACQUAVEL',
        'id': '',
        "documento": 28343227,
        "nivel": 'AFICIONADO',
        "fecha": '29477',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Mariani',
        "nombre": 'Aldo',
        "club": 'BUCOR NATACION',
        'id': '',
        "documento": 14364271,
        "nivel": 'AFICIONADO',
        "fecha": '22317',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 5',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Medina',
        "nombre": 'Lucas',
        "club": 'SPORT AUTOMOVIL CLUB SAN FRANCISCO',
        'id': '',
        "documento": 288401358,
        "nivel": 'AFICIONADO',
        "fecha": '29724',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Demarchi',
        "nombre": 'Andres',
        "club": 'PILETA VIDA ACUATICA SUSANA SCHWANDER',
        'id': '',
        "documento": 32861812,
        "nivel": 'AFICIONADO',
        "fecha": '31865',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Figueroa',
        "nombre": 'Ignacio',
        "club": 'PILETA VIDA ACUATICA SUSANA SCHWANDER',
        'id': '',
        "documento": 31901989,
        "nivel": 'AFICIONADO',
        "fecha": '31348',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Constantino',
        "nombre": 'Paloma',
        "club": 'PILETA VIDA ACUATICA SUSANA SCHWANDER',
        'id': '',
        "documento": 45089327,
        "nivel": 'AFICIONADO',
        "fecha": '37820',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Secchiari ',
        "nombre": 'Eliseo',
        "club": 'PILETA VIDA ACUATICA SUSANA SCHWANDER',
        'id': '',
        "documento": 53322697,
        "nivel": 'AFICIONADO',
        "fecha": '41529',
        "genero": 'MASCULINO',
        "distancia": 750,
        "categoria": 'INFANTIL',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Menichetti',
        "nombre": 'Maria Del Pilar',
        "club": 'PILETA VIDA ACUATICA SUSANA SCHWANDER',
        'id': '',
        "documento": 99999999,
        "nivel": 'AFICIONADO',
        "fecha": '41120',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'MENOR 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Civallero',
        "nombre": 'Sara Beatriz',
        "club": 'EOS DISTRITO DEPORTIVO',
        'id': '',
        "documento": 35963653,
        "nivel": 'AFICIONADO',
        "fecha": '33402',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Cantero',
        "nombre": 'Agustin',
        "club": 'EOS DISTRITO DEPORTIVO',
        'id': '',
        "documento": 44432737,
        "nivel": 'AFICIONADO',
        "fecha": '37531',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Gallego Vega',
        "nombre": 'Ezequiel David',
        "club": 'EOS DISTRITO DEPORTIVO',
        'id': '',
        "documento": 46719251,
        "nivel": 'AFICIONADO',
        "fecha": '38786',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'JUVENIL 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Mercado',
        "nombre": 'Rubén',
        "club": 'EOS DISTRITO DEPORTIVO',
        'id': '',
        "documento": 22941663,
        "nivel": 'AFICIONADO',
        "fecha": '26596',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Gomez Sanchez',
        "nombre": 'Joaquín',
        "club": 'EOS DISTRITO DEPORTIVO',
        'id': '',
        "documento": 51202665,
        "nivel": 'AFICIONADO',
        "fecha": '40682',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'MENOR 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Pleitavino',
        "nombre": 'Gabriela Vanina',
        "club": 'EOS DISTRITO DEPORTIVO',
        'id': '',
        "documento": 30603920,
        "nivel": 'AFICIONADO',
        "fecha": '30765',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Ballester ',
        "nombre": 'Alejo ',
        "club": 'AQUASPORT PILETA DE NATACIÓN ',
        'id': '',
        "documento": 5083655,
        "nivel": 'PROMOCIONAL',
        "fecha": '40582',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'MENOR 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Olmos ',
        "nombre": 'Carola ',
        "club": 'AQUASPORT PILETA DE NATACIÓN ',
        'id': '',
        "documento": 51017039,
        "nivel": 'AFICIONADO',
        "fecha": '40692',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'MENOR 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Pereyra ',
        "nombre": 'Pedro',
        "club": 'AQUASPORT PILETA DE NATACIÓN ',
        'id': '',
        "documento": 52686570,
        "nivel": 'PROMOCIONAL',
        "fecha": '41147',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'MENOR 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Schmidth',
        "nombre": 'Alan ',
        "club": 'AQUASPORT PILETA DE NATACIÓN ',
        'id': '',
        "documento": 50743491,
        "nivel": 'PROMOCIONAL',
        "fecha": '40592',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'MENOR 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Pijuan',
        "nombre": 'Agustin',
        "club": 'AQUASPORT PILETA DE NATACIÓN ',
        'id': '',
        "documento": 49322718,
        "nivel": 'NACIONAL',
        "fecha": '39863',
        "genero": 'MASCULINO',
        "distancia": 5000,
        "categoria": 'ELITE NATACION',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Renjipo ',
        "nombre": 'Maria Sol',
        "club": 'AQUASPORT PILETA DE NATACIÓN ',
        'id': '',
        "documento": 52100059,
        "nivel": 'AFICIONADO',
        "fecha": '40930',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'MENOR 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Reyna Giosso',
        "nombre": 'Virginia ',
        "club": 'AQUASPORT PILETA DE NATACIÓN ',
        'id': '',
        "documento": 50239389,
        "nivel": 'PROMOCIONAL',
        "fecha": '40331',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CADETE 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Perone ',
        "nombre": 'Nicolas Agustin ',
        "club": 'AQUASPORT PILETA DE NATACIÓN ',
        'id': '',
        "documento": 50633558,
        "nivel": 'NACIONAL',
        "fecha": '40331',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CADETE 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Ramallo ',
        "nombre": 'Marta Roxana',
        "club": 'AQUASPORT PILETA DE NATACIÓN ',
        'id': '',
        "documento": 18338462,
        "nivel": 'NACIONAL',
        "fecha": '24772',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'MASTER G',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Pijuan',
        "nombre": 'Ariel Norberto ',
        "club": 'AQUASPORT PILETA DE NATACIÓN ',
        'id': '',
        "documento": 24847177,
        "nivel": 'NACIONAL',
        "fecha": '27692',
        "genero": 'MASCULINO',
        "distancia": 3000,
        "categoria": 'ELITE MASTER',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Fernandez',
        "nombre": 'Claudia',
        "club": 'INSTITUTO JOSÉ PEÑA',
        'id': '',
        "documento": 22563297,
        "nivel": 'AFICIONADO',
        "fecha": '26339',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Racciatti ',
        "nombre": 'Maria Laura',
        "club": 'INSTITUTO JOSÉ PEÑA',
        'id': '',
        "documento": 36144690,
        "nivel": 'AFICIONADO',
        "fecha": '33578',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Casimiro',
        "nombre": 'Nancy',
        "club": 'M.E ENTRENAMIENTO',
        'id': '',
        "documento": 31843907,
        "nivel": 'AFICIONADO',
        "fecha": '31304',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Medina',
        "nombre": 'Mónica',
        "club": 'CEF 11-RIO CUARTO',
        'id': '',
        "documento": 21655413,
        "nivel": 'AFICIONADO',
        "fecha": '25771',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Pesce',
        "nombre": 'Yvanna Valeria',
        "club": 'CEF 11-RIO CUARTO',
        'id': '',
        "documento": 25173450,
        "nivel": 'AFICIONADO',
        "fecha": '27917',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Vrbitza',
        "nombre": 'Mailen Lucía',
        "club": 'CEF 11-RIO CUARTO',
        'id': '',
        "documento": 36887865,
        "nivel": 'AFICIONADO',
        "fecha": '33787',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Azcurra',
        "nombre": 'Ana Paula',
        "club": 'CEF 11-RIO CUARTO',
        'id': '',
        "documento": 43190472,
        "nivel": 'AFICIONADO',
        "fecha": '37007',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Fernandez',
        "nombre": 'Sergio',
        "club": 'CEF 11-RIO CUARTO',
        'id': '',
        "documento": 13951242,
        "nivel": 'AFICIONADO',
        "fecha": '22120',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 5',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Vera',
        "nombre": 'Paul',
        "club": 'ACTITUD FENIX',
        'id': '',
        "documento": 34562745,
        "nivel": 'AFICIONADO',
        "fecha": '32770',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Martinez',
        "nombre": 'Diego',
        "club": 'ACTITUD FENIX',
        'id': '',
        "documento": 23873308,
        "nivel": 'AFICIONADO',
        "fecha": '27079',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Zucchi ',
        "nombre": 'Octavio',
        "club": 'CEF 11 - DEPORTES RIO CUARTO',
        'id': '',
        "documento": 45592762,
        "nivel": 'PROMOCIONAL',
        "fecha": '38139',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Becker',
        "nombre": 'Ignacio',
        "club": 'CEF 11 - DEPORTES RIO CUARTO',
        'id': '',
        "documento": 48129958,
        "nivel": 'PROMOCIONAL',
        "fecha": '39390',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'JUVENIL 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Azcurra ',
        "nombre": 'Catalina',
        "club": 'CEF 11 - DEPORTES RIO CUARTO',
        'id': '',
        "documento": 47464754,
        "nivel": 'PROMOCIONAL',
        "fecha": '38999',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'JUVENIL 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Rocha ',
        "nombre": 'Agostina',
        "club": 'CEF 11 - DEPORTES RIO CUARTO',
        'id': '',
        "documento": 49071571,
        "nivel": 'PROMOCIONAL',
        "fecha": '39278',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'JUVENIL 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Giachero',
        "nombre": 'Mia',
        "club": 'CEF 11 - DEPORTES RIO CUARTO',
        'id': '',
        "documento": 49963832,
        "nivel": 'PROMOCIONAL',
        "fecha": '40176',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CADETE 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Reartes ',
        "nombre": 'Julieta',
        "club": 'CEF 11 - DEPORTES RIO CUARTO',
        'id': '',
        "documento": 50416412,
        "nivel": 'PROMOCIONAL',
        "fecha": '40375',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CADETE 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Moreyra',
        "nombre": 'Abril',
        "club": 'CEF 11 - DEPORTES RIO CUARTO',
        'id': '',
        "documento": 51413820,
        "nivel": 'PROMOCIONAL',
        "fecha": '40816',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'MENOR 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Alvarez',
        "nombre": 'Catalina',
        "club": 'CEF 11 - DEPORTES RIO CUARTO',
        'id': '',
        "documento": 50262525,
        "nivel": 'NACIONAL',
        "fecha": '40311',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CADETE 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Martino',
        "nombre": 'Laura',
        "club": 'BUCOR NATACIÓN',
        'id': '',
        "documento": 26087616,
        "nivel": 'AFICIONADO',
        "fecha": '28421',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Bruno Mirolo',
        "nombre": 'Roxana',
        "club": 'BUCOR NATACIÓN',
        'id': '',
        "documento": 24770498,
        "nivel": 'AFICIONADO',
        "fecha": '27607',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Moyano',
        "nombre": 'Santiago Agustin',
        "club": 'BUCOR NATACIÓN',
        'id': '',
        "documento": 38987193,
        "nivel": 'AFICIONADO',
        "fecha": '34801',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Machado ',
        "nombre": 'Eduardo Bernardo',
        "club": 'BUCOR NATACIÓN',
        'id': '',
        "documento": 32240377,
        "nivel": 'AFICIONADO',
        "fecha": '31527',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Missan',
        "nombre": 'Carlos',
        "club": 'VELEZ',
        'id': '',
        "documento": 53845267,
        "nivel": 'PROMOCIONAL',
        "fecha": '41711',
        "genero": 'MASCULINO',
        "distancia": 750,
        "categoria": 'INFANTIL',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Fioni',
        "nombre": 'Serafin',
        "club": 'VELEZ',
        'id': '',
        "documento": 41813168,
        "nivel": 'AFICIONADO',
        "fecha": '36288',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Dalmasso',
        "nombre": 'Daniel',
        "club": 'VELEZ',
        'id': '',
        "documento": 17247969,
        "nivel": 'AFICIONADO',
        "fecha": '24124',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Rodriguez',
        "nombre": 'Laura',
        "club": 'VELEZ',
        'id': '',
        "documento": 23122028,
        "nivel": 'AFICIONADO',
        "fecha": '26648',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Asnal ',
        "nombre": 'Guadalupe',
        "club": 'C.A.R.S. RIO CUARTO',
        'id': '',
        "documento": 23954262,
        "nivel": 'AFICIONADO',
        "fecha": '27215',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Quiñones',
        "nombre": 'Yomara',
        "club": 'C.A.R.S. RIO CUARTO',
        'id': '',
        "documento": 16373541,
        "nivel": 'AFICIONADO',
        "fecha": '23230',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 5',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Conci',
        "nombre": 'Rocio',
        "club": 'CLUB UNIVERSITARIO CORDOBA',
        'id': '',
        "documento": 38181437,
        "nivel": 'AFICIONADO',
        "fecha": '34452',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Olmos',
        "nombre": 'Gustavo Christian',
        "club": 'CLUB UNIVERSITARIO CORDOBA',
        'id': '',
        "documento": 22565097,
        "nivel": 'AFICIONADO',
        "fecha": '26345',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Burgos Peralta',
        "nombre": 'Francisco',
        "club": 'CLUB UNIVERSITARIO CORDOBA',
        'id': '',
        "documento": 35967953,
        "nivel": 'AFICIONADO',
        "fecha": '33470',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Argibay',
        "nombre": 'Daihana Soledad',
        "club": 'CLUB UNIVERSITARIO CORDOBA',
        'id': '',
        "documento": 35344231,
        "nivel": 'AFICIONADO',
        "fecha": '33192',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Forte',
        "nombre": 'Constanza',
        "club": 'CLUB UNIVERSITARIO CORDOBA',
        'id': '',
        "documento": 48070753,
        "nivel": 'AFICIONADO',
        "fecha": '39401',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'JUVENIL 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Forte',
        "nombre": 'Valentino',
        "club": 'CLUB UNIVERSITARIO CORDOBA',
        'id': '',
        "documento": 50420244,
        "nivel": 'NACIONAL',
        "fecha": '40393',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CADETE 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Funes',
        "nombre": 'Maria Jose',
        "club": 'CLUB UNIVERSITARIO CORDOBA',
        'id': '',
        "documento": 44579861,
        "nivel": 'NACIONAL',
        "fecha": '37653',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'PRE MASTER',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Guntero',
        "nombre": 'Vanina Alejandra',
        "club": 'SPORT AUTOMÓVIL CLUB SAN FRANCISCO',
        'id': '',
        "documento": 30846235,
        "nivel": 'AFICIONADO',
        "fecha": '30799',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Molina',
        "nombre": 'Lucia',
        "club": 'ASOCIACIÓN INDEPENDIENTE DOLORES',
        'id': '',
        "documento": 44975742,
        "nivel": 'AFICIONADO',
        "fecha": '37844',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Caucota',
        "nombre": 'Federico',
        "club": 'EL CLUB',
        'id': '',
        "documento": 25885085,
        "nivel": 'AFICIONADO',
        "fecha": '28350',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Ghiano',
        "nombre": 'Natacha Eugenia',
        "club": 'EL CLUB',
        'id': '',
        "documento": 24120762,
        "nivel": 'AFICIONADO',
        "fecha": '27384',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Ghiano',
        "nombre": 'Christian Gustavo',
        "club": 'EL CLUB',
        'id': '',
        "documento": 22374056,
        "nivel": 'AFICIONADO',
        "fecha": '26229',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'González Dondo',
        "nombre": 'Diego',
        "club": 'EL CLUB',
        'id': '',
        "documento": 31222887,
        "nivel": 'AFICIONADO',
        "fecha": '30950',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Rodriguez',
        "nombre": 'Leonardo Hugo',
        "club": 'EL CLUB',
        'id': '',
        "documento": 27171509,
        "nivel": 'AFICIONADO',
        "fecha": '28907',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Rescala ',
        "nombre": 'Adriana ',
        "club": 'EL CLUB',
        'id': '',
        "documento": 29943178,
        "nivel": 'AFICIONADO',
        "fecha": '30382',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'González ',
        "nombre": 'Norma ',
        "club": 'EL CLUB',
        'id': '',
        "documento": 17115135,
        "nivel": 'AFICIONADO',
        "fecha": '23693',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 5',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Leyria ',
        "nombre": 'Ángel ',
        "club": 'EL CLUB',
        'id': '',
        "documento": 24655189,
        "nivel": 'AFICIONADO',
        "fecha": '27607',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Bongiorno ',
        "nombre": 'Guillermo ',
        "club": 'EL CLUB',
        'id': '',
        "documento": 16083579,
        "nivel": 'AFICIONADO',
        "fecha": '22818',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 5',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Cappellotto ',
        "nombre": 'Juan ',
        "club": 'EL CLUB',
        'id': '',
        "documento": 26718575,
        "nivel": 'AFICIONADO',
        "fecha": '28557',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'D Ambra ',
        "nombre": 'Eduardo ',
        "club": 'EL CLUB',
        'id': '',
        "documento": 10249408,
        "nivel": 'AFICIONADO',
        "fecha": '19081',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 6',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Vovard ',
        "nombre": 'Cristian ',
        "club": 'EL CLUB',
        'id': '',
        "documento": 24018794,
        "nivel": 'AFICIONADO',
        "fecha": '27440',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Romero',
        "nombre": 'Nelba Noemi',
        "club": 'EL CLUB',
        'id': '',
        "documento": 14366038,
        "nivel": 'AFICIONADO',
        "fecha": '22267',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 5',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Toledo',
        "nombre": 'Fernando',
        "club": 'EL CLUB',
        'id': '',
        "documento": 20268168,
        "nivel": 'AFICIONADO',
        "fecha": '24915',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 4',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Martino',
        "nombre": 'Laura',
        "club": 'BUCOR NATACION',
        'id': '',
        "documento": 26087616,
        "nivel": 'AFICIONADO',
        "fecha": '28421',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Mirolo',
        "nombre": 'Roxana',
        "club": 'BUCOR NATACION',
        'id': '',
        "documento": 24770498,
        "nivel": 'AFICIONADO',
        "fecha": '27402',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Moyano ',
        "nombre": 'Santiago',
        "club": 'BUCOR NATACION',
        'id': '',
        "documento": 38987193,
        "nivel": 'AFICIONADO',
        "fecha": '34711',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Machado Zorrilla',
        "nombre": 'Bernardo',
        "club": 'BUCOR NATACION',
        'id': '',
        "documento": 32240377,
        "nivel": 'AFICIONADO',
        "fecha": '31527',
        "genero": 'MASCULINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Mariani',
        "nombre": 'Aldo',
        "club": 'BUCOR NATACION',
        'id': '',
        "documento": 14364271,
        "nivel": 'AFICIONADO',
        "fecha": '22403',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 5',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Terenzano ',
        "nombre": 'María Isabel',
        "club": 'CÍRCULO FUERZA AÉREA - CÓRDOBA',
        'id': '',
        "documento": 13384755,
        "nivel": 'NACIONAL',
        "fecha": '21140',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'MASTER I',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Bergia',
        "nombre": 'Oscar Alberto',
        "club": 'CÍRCULO FUERZA AÉREA - CÓRDOBA',
        'id': '',
        "documento": 11212340,
        "nivel": 'NACIONAL',
        "fecha": '19920',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'MASTER J',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Herrera',
        "nombre": 'Norma Beatríz',
        "club": 'CÍRCULO FUERZA AÉREA - CÓRDOBA',
        'id': '',
        "documento": 12872753,
        "nivel": 'NACIONAL',
        "fecha": '20731',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'MASTER I',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Maggi',
        "nombre": 'Enrique ',
        "club": 'CLUB ATLETICO UNIÓN DE SUNCHALES - SANTA FE',
        'id': '',
        "documento": 8323336,
        "nivel": 'AFICIONADO',
        "fecha": '18736',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'CATEGORIA 6',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Corrales',
        "nombre": 'Matilda',
        "club": 'BUCOR',
        'id': '',
        "documento": 50334209,
        "nivel": 'PROMOCIONAL',
        "fecha": '40710',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'MENOR 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Gorgobea',
        "nombre": 'Olivia',
        "club": 'BUCOR',
        'id': '',
        "documento": 50939496,
        "nivel": 'PROMOCIONAL',
        "fecha": '40687',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'MENOR 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Rivero',
        "nombre": 'Ema',
        "club": 'BUCOR',
        'id': '',
        "documento": 50080571,
        "nivel": 'PROMOCIONAL',
        "fecha": '40198',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CADETE 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Notafranceso',
        "nombre": 'Donata',
        "club": 'BUCOR',
        'id': '',
        "documento": 49625150,
        "nivel": 'PROMOCIONAL',
        "fecha": '40062',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'CADETE 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Caceres',
        "nombre": 'Uriel',
        "club": 'BUCOR',
        'id': '',
        "documento": 52157490,
        "nivel": 'PROMOCIONAL',
        "fecha": '40983',
        "genero": 'MASCULINO',
        "distancia": 1500,
        "categoria": 'MENOR 1',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Baltazar',
        "nombre": 'Mia',
        "club": 'BUCOR',
        'id': '',
        "documento": 50629613,
        "nivel": 'PROMOCIONAL',
        "fecha": '40577',
        "genero": 'FEMENINO',
        "distancia": 1500,
        "categoria": 'MENOR 2',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Almada ',
        "nombre": 'Lautaro',
        "club": 'BUCOR',
        'id': '',
        "documento": 47320157,
        "nivel": 'NACIONAL',
        "fecha": '9/21/2006',
        "genero": 'MASCULINO',
        "distancia": 5000,
        "categoria": 'ELITE NATACION',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Rodriguez',
        "nombre": 'Tomas',
        "club": 'BUCOR',
        'id': '',
        "documento": 46127845,
        "nivel": 'NACIONAL',
        "fecha": '38423',
        "genero": 'MASCULINO',
        "distancia": 5000,
        "categoria": 'ELITE NATACION',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Saba',
        "nombre": 'Delfina',
        "club": 'BUCOR',
        'id': '',
        "documento": 47001622,
        "nivel": 'NACIONAL',
        "fecha": '38823',
        "genero": 'FEMENINO',
        "distancia": 5000,
        "categoria": 'ELITE NATACION',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Hormaeche',
        "nombre": 'Sol',
        "club": 'BUCOR',
        'id': '',
        "documento": 46658212,
        "nivel": 'NACIONAL',
        "fecha": '6/20/2006',
        "genero": 'FEMENINO',
        "distancia": 5000,
        "categoria": 'ELITE NATACION',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Salinas ',
        "nombre": 'Lucas',
        "club": 'BUCOR',
        'id': '',
        "documento": 46310922,
        "nivel": 'NACIONAL',
        "fecha": '7/13/2005',
        "genero": 'MASCULINO',
        "distancia": 5000,
        "categoria": 'ELITE NATACION',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },
    {
        "apellido": 'Nieto',
        "nombre": 'Matilda',
        "club": 'BUCOR',
        'id': '',
        "documento": 24691710,
        "nivel": 'AFICIONADO',
        "fecha": '27536',
        "genero": 'FEMENINO',
        "distancia": 2250,
        "categoria": 'CATEGORIA 3',
        "tiempo": 9999999,
        "tiempoFormat": '-'
    },




]