const nadadores = [{
    "apellido": "Manassero",
    "nombre": "Paulina",
    "club": "Deheza Fotball Club",
    "id": "",
    "documento": 57782494,
    "nivel": "AFICIONADO",
    "fecha": "41854",
    "genero": "FEMENINO",
    "distancia": 750,
    "categoria": "INFANTIL",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Missan",
    "nombre": "Carlos",
    "club": "Velez",
    "id": "",
    "documento": 53845267,
    "nivel": "AFICIONADO",
    "fecha": "41711",
    "genero": "MASCULINO",
    "distancia": 750,
    "categoria": "INFANTIL",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Baer",
    "nombre": "Emilia",
    "club": "RED STAR",
    "id": "",
    "documento": 54117607,
    "nivel": "PROMOCIONAL",
    "fecha": "41823",
    "genero": "FEMENINO",
    "distancia": 750,
    "categoria": "INFANTIL",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Zalazar",
    "nombre": "Maria Paz",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 53320575,
    "nivel": "PROMOCIONAL",
    "fecha": "41470",
    "genero": "FEMENINO",
    "distancia": 750,
    "categoria": "INFANTIL",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Almada",
    "nombre": "Sofia",
    "club": "RED STAR",
    "id": "",
    "documento": 53035223,
    "nivel": "PROMOCIONAL",
    "fecha": "41351",
    "genero": "FEMENINO",
    "distancia": 750,
    "categoria": "INFANTIL",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Arias",
    "nombre": "Tatiana",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 53098873,
    "nivel": "PROMOCIONAL",
    "fecha": "41408",
    "genero": "FEMENINO",
    "distancia": 750,
    "categoria": "INFANTIL",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Iriarte",
    "nombre": "Benicio",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 54256448,
    "nivel": "PROMOCIONAL",
    "fecha": "41898",
    "genero": "MASCULINO",
    "distancia": 750,
    "categoria": "INFANTIL",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gerbaudo Baro",
    "nombre": "Francisco A.",
    "club": "Jockey Ckub Córdoba",
    "id": "",
    "documento": 52863162,
    "nivel": "PROMOCIONAL",
    "fecha": "41341",
    "genero": "MASCULINO",
    "distancia": 750,
    "categoria": "INFANTIL",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Olmos",
    "nombre": "Carola",
    "club": "AQUASPORT",
    "id": "",
    "documento": 51017039,
    "nivel": "AFICIONADO",
    "fecha": "40692",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Bergamasco",
    "nombre": "Adelina",
    "club": "Deheza Fotball Club",
    "id": "",
    "documento": 49768329,
    "nivel": "AFICIONADO",
    "fecha": "40391",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CADETE 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Stantero",
    "nombre": "Agustin",
    "club": "CLUB LIBERTADOR MASTER",
    "id": "",
    "documento": 50154948,
    "nivel": "AFICIONADO",
    "fecha": "40255",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CADETE 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "SALANITRO",
    "nombre": "Timoteo",
    "club": "CLUB ATLETICO ADELIA MARIA",
    "id": "",
    "documento": 50334665,
    "nivel": "AFICIONADO",
    "fecha": "40312",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CADETE 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Berardi",
    "nombre": "Ignacio",
    "club": "Deheza Fotball Club",
    "id": "",
    "documento": 49619280,
    "nivel": "AFICIONADO",
    "fecha": "40023",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CADETE 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Rodriguez",
    "nombre": "Leon",
    "club": "SAN ISIDRO CLUB",
    "id": "",
    "documento": 49557706,
    "nivel": "AFICIONADO",
    "fecha": "39977",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CADETE 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Cabrero",
    "nombre": "Ana Laura",
    "club": "CLUB UNIVERSITARIO CORDOBA",
    "id": "",
    "documento": 40297469,
    "nivel": "AFICIONADO",
    "fecha": "35557",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Berardi",
    "nombre": "Antonella",
    "club": "Deheza Fotball Club",
    "id": "",
    "documento": 43927989,
    "nivel": "AFICIONADO",
    "fecha": "37410",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Molina",
    "nombre": "Lucia",
    "club": "Asociación Independiente Dolores",
    "id": "",
    "documento": 44975742,
    "nivel": "AFICIONADO",
    "fecha": "37844",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": " Salcedo",
    "nombre": "Macarena Belen",
    "club": "instituto  atlec central cordoba",
    "id": "",
    "documento": 39623602,
    "nivel": "AFICIONADO",
    "fecha": "35235",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Rondan",
    "nombre": "Milena",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 43808007,
    "nivel": "AFICIONADO",
    "fecha": "37312",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Sanchez",
    "nombre": "Carolina",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 36124876,
    "nivel": "AFICIONADO",
    "fecha": "33396",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Racciatti",
    "nombre": "Ma Laura",
    "club": "José Peña",
    "id": "",
    "documento": 36144690,
    "nivel": "AFICIONADO",
    "fecha": "33401",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Vrbitza",
    "nombre": "Mailen Lucía",
    "club": "CEF 11-RIO CUARTO",
    "id": "",
    "documento": 36887865,
    "nivel": "AFICIONADO",
    "fecha": "33787",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Otero",
    "nombre": "Maria Del Carmen",
    "club": "sol y lago",
    "id": "",
    "documento": 31952532,
    "nivel": "AFICIONADO",
    "fecha": "31443",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Conci",
    "nombre": "Rocio",
    "club": "CLUB UNIVERSITARIO CORDOBA",
    "id": "",
    "documento": 38181437,
    "nivel": "AFICIONADO",
    "fecha": "34452",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Fagotti",
    "nombre": "Agustin",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 32907156,
    "nivel": "AFICIONADO",
    "fecha": "31863",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Zurita",
    "nombre": "Diego Matias",
    "club": "CLUB UNIVERSITARIO CORDOBA",
    "id": "",
    "documento": 34841070,
    "nivel": "AFICIONADO",
    "fecha": "32800",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Burgos Peralta",
    "nombre": "Francisco Gabriel",
    "club": "CLUB UNIVERSITARIO CORDOBA",
    "id": "",
    "documento": 35967953,
    "nivel": "AFICIONADO",
    "fecha": "33470",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Ribotta",
    "nombre": "Juan Pablo",
    "club": "instituto  atlec central cordoba",
    "id": "",
    "documento": 36354513,
    "nivel": "AFICIONADO",
    "fecha": "33748",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Hrenadiez",
    "nombre": "Mauro",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 31749932,
    "nivel": "AFICIONADO",
    "fecha": "31272",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Herrera",
    "nombre": "Norberto Emilio",
    "club": "Spot Swim & Training",
    "id": "",
    "documento": 33271369,
    "nivel": "AFICIONADO",
    "fecha": "32087",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Vedromick",
    "nombre": "Sergio",
    "club": "CLUB A GARIBALDI",
    "id": "",
    "documento": 238482211,
    "nivel": "AFICIONADO",
    "fecha": "27245",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Caffaratti",
    "nombre": "Alicia",
    "club": "Velez",
    "id": "",
    "documento": 29567780,
    "nivel": "AFICIONADO",
    "fecha": "30331",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Peters",
    "nombre": "Ana",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 24352548,
    "nivel": "AFICIONADO",
    "fecha": "27443",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gallego",
    "nombre": "Carina",
    "club": "Deheza Fotball Club",
    "id": "",
    "documento": 28888734,
    "nivel": "AFICIONADO",
    "fecha": "29846",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Bianchi",
    "nombre": "Claudia",
    "club": "ATLANTIS",
    "id": "",
    "documento": 2461465,
    "nivel": "AFICIONADO",
    "fecha": "27585",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Villanueva",
    "nombre": "Elena",
    "club": "Deheza Fotball Club",
    "id": "",
    "documento": 29761465,
    "nivel": "AFICIONADO",
    "fecha": "30349",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Melegatti",
    "nombre": "Gisela",
    "club": "RED STAR",
    "id": "",
    "documento": 30271846,
    "nivel": "AFICIONADO",
    "fecha": "30617",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Fleytas",
    "nombre": "Ivan",
    "club": "RED STAR",
    "id": "",
    "documento": 26171168,
    "nivel": "AFICIONADO",
    "fecha": "28405",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Saenz",
    "nombre": "Julieta",
    "club": "Natatorio climatizado v.d",
    "id": "",
    "documento": 25456866,
    "nivel": "AFICIONADO",
    "fecha": "28103",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gonzalez Scapin",
    "nombre": "Maria Lorena",
    "club": "AFICIONADO EN CORED",
    "id": "",
    "documento": 29176656,
    "nivel": "AFICIONADO",
    "fecha": "29947",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Trabanco",
    "nombre": "Miriam",
    "club": "CEF 11-RIO CUARTO",
    "id": "",
    "documento": 28230861,
    "nivel": "AFICIONADO",
    "fecha": "29383",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Garcia",
    "nombre": "Romina",
    "club": "SAN ISIDRO CLUB",
    "id": "",
    "documento": 29500729,
    "nivel": "AFICIONADO",
    "fecha": "30079",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Setti",
    "nombre": "Silvana",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 27070561,
    "nivel": "AFICIONADO",
    "fecha": "28849",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Noriega",
    "nombre": "Silvia Daniela",
    "club": "Spot Swim & Training",
    "id": "",
    "documento": 26903577,
    "nivel": "AFICIONADO",
    "fecha": "28767",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Noriega",
    "nombre": "Soledad",
    "club": "Spot Swim & Training",
    "id": "",
    "documento": 29110144,
    "nivel": "AFICIONADO",
    "fecha": "29858",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Pesce",
    "nombre": "Yvanna Valeria",
    "club": "CEF 11-RIO CUARTO",
    "id": "",
    "documento": 25173450,
    "nivel": "AFICIONADO",
    "fecha": "27917",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Leyria",
    "nombre": "Ángel",
    "club": "El Club",
    "id": "",
    "documento": 24655189,
    "nivel": "AFICIONADO",
    "fecha": "27607",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Vovard",
    "nombre": "Cristian",
    "club": "El Club",
    "id": "",
    "documento": 24018794,
    "nivel": "AFICIONADO",
    "fecha": "27440",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Conci",
    "nombre": "Federico",
    "club": "HEED",
    "id": "",
    "documento": 29252993,
    "nivel": "AFICIONADO",
    "fecha": "30000",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Alonso Figueroa",
    "nombre": "Gaston Horacio",
    "club": "instituto  atlec central cordoba",
    "id": "",
    "documento": 26480758,
    "nivel": "AFICIONADO",
    "fecha": "28550",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Rodriguez",
    "nombre": "Juan Pablo",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 28042181,
    "nivel": "AFICIONADO",
    "fecha": "29289",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Berardi",
    "nombre": "Juan Ramón",
    "club": "Deheza Fotball Club",
    "id": "",
    "documento": 25207556,
    "nivel": "AFICIONADO",
    "fecha": "28080",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Rodriguez",
    "nombre": "Leonardo Hugo",
    "club": "El Club",
    "id": "",
    "documento": 27171509,
    "nivel": "AFICIONADO",
    "fecha": "28907",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Magnano",
    "nombre": "Gabriela",
    "club": "HEED",
    "id": "",
    "documento": 20699361,
    "nivel": "AFICIONADO",
    "fecha": "25353",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Mestre",
    "nombre": "Ivone",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 169264995,
    "nivel": "AFICIONADO",
    "fecha": "23866",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Rodriguez",
    "nombre": "Laura",
    "club": "Velez",
    "id": "",
    "documento": 23122028,
    "nivel": "AFICIONADO",
    "fecha": "26648",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Bonaldi",
    "nombre": "Mariana",
    "club": "SAN ISIDRO CLUB",
    "id": "",
    "documento": 21967905,
    "nivel": "AFICIONADO",
    "fecha": "25924",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Medina",
    "nombre": "Mónica",
    "club": "CEF 11-RIO CUARTO",
    "id": "",
    "documento": 21655413,
    "nivel": "AFICIONADO",
    "fecha": "25771",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Dubuoloy",
    "nombre": "Natalia",
    "club": "sol y lago",
    "id": "",
    "documento": 23290320,
    "nivel": "AFICIONADO",
    "fecha": "26861",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Oliva",
    "nombre": "Alejandro Javier",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 23794485,
    "nivel": "AFICIONADO",
    "fecha": "27088",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Marquez",
    "nombre": "Ariel",
    "club": "ATLANTIS",
    "id": "",
    "documento": 24089318,
    "nivel": "AFICIONADO",
    "fecha": "27254",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Dalmasso",
    "nombre": "Daniel",
    "club": "Velez",
    "id": "",
    "documento": 17247969,
    "nivel": "AFICIONADO",
    "fecha": "24124",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Olmos",
    "nombre": "Gustavo Christian",
    "club": "CLUB UNIVERSITARIO CORDOBA",
    "id": "",
    "documento": 22565097,
    "nivel": "AFICIONADO",
    "fecha": "26345",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Grosso",
    "nombre": "Andrea",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 16654289,
    "nivel": "AFICIONADO",
    "fecha": "23572",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Pizarro",
    "nombre": "Estela",
    "club": "sol y lago",
    "id": "",
    "documento": 13680934,
    "nivel": "AFICIONADO",
    "fecha": "21824",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "González",
    "nombre": "Norma",
    "club": "El Club",
    "id": "",
    "documento": 17115135,
    "nivel": "AFICIONADO",
    "fecha": "23693",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Bongiorno",
    "nombre": "Guillermo",
    "club": "El Club",
    "id": "",
    "documento": 16083579,
    "nivel": "AFICIONADO",
    "fecha": "22818",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Schneider",
    "nombre": "Julio",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 13682678,
    "nivel": "AFICIONADO",
    "fecha": "21786",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Valiente",
    "nombre": "Miguel",
    "club": "El Club",
    "id": "",
    "documento": 12996898,
    "nivel": "AFICIONADO",
    "fecha": "21591",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "D Ambra",
    "nombre": "Eduardo",
    "club": "El Club",
    "id": "",
    "documento": 10249408,
    "nivel": "AFICIONADO",
    "fecha": "19081",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 6",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Maggi",
    "nombre": "Enrique",
    "club": "Spot Swim & Training",
    "id": "",
    "documento": 8323336,
    "nivel": "AFICIONADO",
    "fecha": "18736",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CATEGORIA 6",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Brussa    ",
    "nombre": "Valentino",
    "club": "ac. nat. oscar garcia",
    "id": "",
    "documento": 47913453,
    "nivel": "AFICIONADO",
    "fecha": "39188",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "JUVENIL 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Rossi",
    "nombre": "Pablo",
    "club": "Sitas",
    "id": "",
    "documento": 31868952,
    "nivel": "NACIONAL",
    "fecha": "31344",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MASTER C",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Mena",
    "nombre": "Facundo",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 33666329,
    "nivel": "NACIONAL",
    "fecha": "32311",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MASTER C",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Ayrolo",
    "nombre": "Julieta",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 25436454,
    "nivel": "NACIONAL",
    "fecha": "28026",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MASTER E",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Guevara",
    "nombre": "Nestor",
    "club": "SAN ISIDRO CLUB",
    "id": "",
    "documento": 24357654,
    "nivel": "NACIONAL",
    "fecha": "27389",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MASTER F",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Terenzano",
    "nombre": "María Isabel",
    "club": "CÍRCULO FUERZA AÉREA - CÓRDOBA",
    "id": "",
    "documento": 13384755,
    "nivel": "NACIONAL",
    "fecha": "21140",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MASTER I",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Herrera",
    "nombre": "Norma Beatríz",
    "club": "CÍRCULO FUERZA AÉREA - CÓRDOBA",
    "id": "",
    "documento": 12872753,
    "nivel": "NACIONAL",
    "fecha": "20731",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MASTER I",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Iriarte",
    "nombre": "Alma",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 52111992,
    "nivel": "PROMOCIONAL",
    "fecha": "40952",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MENOR 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Oliva",
    "nombre": "Alma",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 52471265,
    "nivel": "PROMOCIONAL",
    "fecha": "41043",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MENOR 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Castro",
    "nombre": "Candela",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 52473069,
    "nivel": "PROMOCIONAL",
    "fecha": "41122",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MENOR 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Fischer",
    "nombre": "Blas",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 52471225,
    "nivel": "PROMOCIONAL",
    "fecha": "41043",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MENOR 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "De Benitez",
    "nombre": "Francisco",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 52471083,
    "nivel": "PROMOCIONAL",
    "fecha": "41086",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MENOR 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Juarez",
    "nombre": "Francisco",
    "club": "ATLANTIS",
    "id": "",
    "documento": 5220011,
    "nivel": "PROMOCIONAL",
    "fecha": "40969",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MENOR 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Alaniz",
    "nombre": "Jeremias",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 52475344,
    "nivel": "PROMOCIONAL",
    "fecha": "41266",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MENOR 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Pereyra",
    "nombre": "Pedro",
    "club": "AQUASPORT",
    "id": "",
    "documento": 52686570,
    "nivel": "PROMOCIONAL",
    "fecha": "41147",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MENOR 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Caceres",
    "nombre": "Uriel",
    "club": "BUCOR",
    "id": "",
    "documento": 52157490,
    "nivel": "PROMOCIONAL",
    "fecha": "40983",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MENOR 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Brunori",
    "nombre": "Alegra",
    "club": "ATLANTIS",
    "id": "",
    "documento": 5052288,
    "nivel": "PROMOCIONAL",
    "fecha": "40849",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gerbaudo",
    "nombre": "Ana Lucia",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 51200648,
    "nivel": "PROMOCIONAL",
    "fecha": "40702",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Corrales",
    "nombre": "Matilda",
    "club": "BUCOR",
    "id": "",
    "documento": 50334209,
    "nivel": "PROMOCIONAL",
    "fecha": "40710",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Baltazar",
    "nombre": "Mia",
    "club": "BUCOR",
    "id": "",
    "documento": 50629613,
    "nivel": "PROMOCIONAL",
    "fecha": "40577",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gorbea",
    "nombre": "Olivia",
    "club": "BUCOR",
    "id": "",
    "documento": 50939496,
    "nivel": "PROMOCIONAL",
    "fecha": "40687",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Franchello",
    "nombre": "Valentina",
    "club": "BUCOR",
    "id": "",
    "documento": 51035178,
    "nivel": "PROMOCIONAL",
    "fecha": "40623",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Schmidth",
    "nombre": "Alan",
    "club": "AQUASPORT",
    "id": "",
    "documento": 50743491,
    "nivel": "PROMOCIONAL",
    "fecha": "40592",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Ballester",
    "nombre": "Alejo",
    "club": "AQUASPORT",
    "id": "",
    "documento": 5083655,
    "nivel": "PROMOCIONAL",
    "fecha": "40582",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Oviedo",
    "nombre": "Bautista",
    "club": "HEED",
    "id": "",
    "documento": 50628243,
    "nivel": "PROMOCIONAL",
    "fecha": "40544",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Milton",
    "nombre": "Lautaro",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 51535565,
    "nivel": "PROMOCIONAL",
    "fecha": "40837",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Romero",
    "nombre": "Mateo",
    "club": "Jockey Ckub Córdoba",
    "id": "",
    "documento": 50853717,
    "nivel": "PROMOCIONAL",
    "fecha": "40597",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "MENOR 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Borgiani",
    "nombre": "Eugenia",
    "club": "ac. nat. oscar garcia",
    "id": "",
    "documento": 50090765,
    "nivel": "PROMOCIONAL",
    "fecha": "40253",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CADETE 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Almada",
    "nombre": "Juan",
    "club": "Club Red Star",
    "id": "",
    "documento": 50697501,
    "nivel": "PROMOCIONAL",
    "fecha": "40437",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CADETE 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Fleytas",
    "nombre": "Berenice",
    "club": "RED STAR",
    "id": "",
    "documento": 48818266,
    "nivel": "PROMOCIONAL",
    "fecha": "40087",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CADETE 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Notarfrancesco",
    "nombre": "Donata",
    "club": "BUCOR",
    "id": "",
    "documento": 49625150,
    "nivel": "PROMOCIONAL",
    "fecha": "40062",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "CADETE 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Marquez",
    "nombre": "Facundo",
    "club": "ATLANTIS",
    "id": "",
    "documento": 49497288,
    "nivel": "PROMOCIONAL",
    "fecha": "39991",
    "genero": "MASCULINO",
    "distancia": 1500,
    "categoria": "CADETE 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Tejada",
    "nombre": "Antonella",
    "club": "Deheza Fotball Club",
    "id": "",
    "documento": 48966515,
    "nivel": "PROMOCIONAL",
    "fecha": "39455",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "JUVENIL 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Cena",
    "nombre": "Celeste",
    "club": "ATLANTIS",
    "id": "",
    "documento": 46719459,
    "nivel": "PROMOCIONAL",
    "fecha": "39042",
    "genero": "FEMENINO",
    "distancia": 1500,
    "categoria": "JUVENIL 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Azcurra",
    "nombre": "Ana Paula",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 43190472,
    "nivel": "AFICIONADO",
    "fecha": "37007",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Cuello",
    "nombre": "Lucila",
    "club": "CLUB ATLETICO ADELIA MARIA",
    "id": "",
    "documento": 40816635,
    "nivel": "AFICIONADO",
    "fecha": "35926",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Saracco",
    "nombre": "Maria Laura",
    "club": "CLUB ATLETICO ADELIA MARIA",
    "id": "",
    "documento": 39472015,
    "nivel": "AFICIONADO",
    "fecha": "35104",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Olmedo",
    "nombre": "Mariano",
    "club": "Jockey Ckub Córdoba",
    "id": "",
    "documento": 44346788,
    "nivel": "AFICIONADO",
    "fecha": "37553",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gallara",
    "nombre": "Nicolas",
    "club": "sol y lago",
    "id": "",
    "documento": 45702352,
    "nivel": "AFICIONADO",
    "fecha": "38198",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Argibay",
    "nombre": "Daihana Soledad",
    "club": "CLUB UNIVERSITARIO CORDOBA",
    "id": "",
    "documento": 35344231,
    "nivel": "AFICIONADO",
    "fecha": "33192",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Mercado",
    "nombre": "Juliana",
    "club": "natatorio climatizado v.d",
    "id": "",
    "documento": 36692089,
    "nivel": "AFICIONADO",
    "fecha": "33884",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Panella",
    "nombre": "Luciana",
    "club": "CARRERA AVENTURA",
    "id": "",
    "documento": 32208320,
    "nivel": "AFICIONADO",
    "fecha": "31548",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Carri",
    "nombre": "Macarena Belén",
    "club": "Spot Swim & Training",
    "id": "",
    "documento": 37524821,
    "nivel": "AFICIONADO",
    "fecha": "34286",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Meza",
    "nombre": "María De Los Ángeles",
    "club": "El Club",
    "id": "",
    "documento": 32373664,
    "nivel": "AFICIONADO",
    "fecha": "31630",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Sorello",
    "nombre": "Maria Virginia",
    "club": "instituto  atlec central cordoba",
    "id": "",
    "documento": 31591926,
    "nivel": "AFICIONADO",
    "fecha": "31281",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Schroter",
    "nombre": "Sofia",
    "club": "CLUB ATLETICO ADELIA MARIA",
    "id": "",
    "documento": 38022303,
    "nivel": "AFICIONADO",
    "fecha": "34468",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gorlero",
    "nombre": "Daniel",
    "club": "ATLANTIS",
    "id": "",
    "documento": 36478862,
    "nivel": "AFICIONADO",
    "fecha": "33552",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Donadio",
    "nombre": "Emiliano Gaston",
    "club": "CLUB ATLETICO ADELIA MARIA",
    "id": "",
    "documento": 36794263,
    "nivel": "AFICIONADO",
    "fecha": "33816",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Bossio",
    "nombre": "Facundo",
    "club": "CLUB ATLETICO ADELIA MARIA",
    "id": "",
    "documento": 37167291,
    "nivel": "AFICIONADO",
    "fecha": "34163",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Santillan Gatti",
    "nombre": "Facundo",
    "club": "El Club",
    "id": "",
    "documento": 37126038,
    "nivel": "AFICIONADO",
    "fecha": "34028",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Llorens Molina",
    "nombre": "Federico Alberto",
    "club": "CLUB ATLETICO ADELIA MARIA",
    "id": "",
    "documento": 34916316,
    "nivel": "AFICIONADO",
    "fecha": "32947",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Rodriguez",
    "nombre": "Fernando",
    "club": "natatorio climatizado v.d.",
    "id": "",
    "documento": 31844518,
    "nivel": "AFICIONADO",
    "fecha": "31116",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Marinelli",
    "nombre": "Francisco",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 37771371,
    "nivel": "AFICIONADO",
    "fecha": "32899",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Palacio",
    "nombre": "Franco",
    "club": "CLUB ATLETICO ADELIA MARIA",
    "id": "",
    "documento": 36794280,
    "nivel": "AFICIONADO",
    "fecha": "33855",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Kendziura",
    "nombre": "Franco Martin",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 33247667,
    "nivel": "AFICIONADO",
    "fecha": "32080",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Silva Braz",
    "nombre": "Rafael",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 26019315,
    "nivel": "AFICIONADO",
    "fecha": "32920",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Jose",
    "nombre": "Salvador",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 34583191,
    "nivel": "AFICIONADO",
    "fecha": "32865",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Rescala",
    "nombre": "Adriana",
    "club": "El Club",
    "id": "",
    "documento": 29943178,
    "nivel": "AFICIONADO",
    "fecha": "30382",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Sioli",
    "nombre": "Eliana",
    "club": "natatorio climatizado v.d",
    "id": "",
    "documento": 26435077,
    "nivel": "AFICIONADO",
    "fecha": "28511",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Fernandez",
    "nombre": "Melina Luciana",
    "club": "Spot Swim & Training",
    "id": "",
    "documento": 30285667,
    "nivel": "AFICIONADO",
    "fecha": "30510",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Bertetti",
    "nombre": "Adrian",
    "club": "HEED",
    "id": "",
    "documento": 24367650,
    "nivel": "AFICIONADO",
    "fecha": "27414",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Cobo Gordillo",
    "nombre": "Antonio",
    "club": "El Club",
    "id": "",
    "documento": 28432907,
    "nivel": "AFICIONADO",
    "fecha": "29595",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "González Dondo",
    "nombre": "Diego",
    "club": "El Club",
    "id": "",
    "documento": 31222887,
    "nivel": "AFICIONADO",
    "fecha": "30950",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Caucota",
    "nombre": "Federico",
    "club": "El Club",
    "id": "",
    "documento": 25885085,
    "nivel": "AFICIONADO",
    "fecha": "28350",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gonzalez",
    "nombre": "Gabriel",
    "club": "CARRERA AVENTURA",
    "id": "",
    "documento": 28058069,
    "nivel": "AFICIONADO",
    "fecha": "29276",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Benedetti",
    "nombre": "Guillermo",
    "club": "natatorio climatizado v.d.",
    "id": "",
    "documento": 30888008,
    "nivel": "AFICIONADO",
    "fecha": "30770",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Cappellotto",
    "nombre": "Juan Ignacio",
    "club": "El Club",
    "id": "",
    "documento": 26718575,
    "nivel": "AFICIONADO",
    "fecha": "28705",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Menossi",
    "nombre": "Maximiliano",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 25136608,
    "nivel": "AFICIONADO",
    "fecha": "27911",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Stantero",
    "nombre": "Silvio",
    "club": "CLUB LIBERTADOR MASTER",
    "id": "",
    "documento": 26952947,
    "nivel": "AFICIONADO",
    "fecha": "28780",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 3",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Fernandez",
    "nombre": "Claudia",
    "club": " José Peña",
    "id": "",
    "documento": 22563297,
    "nivel": "AFICIONADO",
    "fecha": "26574",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Helale",
    "nombre": "Gabriela",
    "club": "Jockey Ckub Córdoba",
    "id": "",
    "documento": 23105845,
    "nivel": "AFICIONADO",
    "fecha": "26671",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Ghiano",
    "nombre": "Natacha Eugenia",
    "club": "El Club",
    "id": "",
    "documento": 24120762,
    "nivel": "AFICIONADO",
    "fecha": "27384",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Varga",
    "nombre": "Patricia",
    "club": "natatorio climatizado v.d.",
    "id": "",
    "documento": 23149349,
    "nivel": "AFICIONADO",
    "fecha": "26711",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Pineda",
    "nombre": "Álvaro",
    "club": "El Club",
    "id": "",
    "documento": 22564446,
    "nivel": "AFICIONADO",
    "fecha": "26357",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gutierrez",
    "nombre": "Carlos",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 21999684,
    "nivel": "AFICIONADO",
    "fecha": "26387",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": " Salcedo",
    "nombre": "Christian Gustavo",
    "club": "El Club",
    "id": "",
    "documento": 22374056,
    "nivel": "AFICIONADO",
    "fecha": "26229",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Frey",
    "nombre": "Walter Hugo",
    "club": "CLUB UNIVERSITARIO CORDOBA",
    "id": "",
    "documento": 18063413,
    "nivel": "AFICIONADO",
    "fecha": "24359",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 4",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Morales",
    "nombre": "Marcela",
    "club": "SAN ISIDRO CLUB",
    "id": "",
    "documento": 18174000,
    "nivel": "AFICIONADO",
    "fecha": "20920",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Cepulver",
    "nombre": " Walter",
    "club": "HEED",
    "id": "",
    "documento": 16228566,
    "nivel": "AFICIONADO",
    "fecha": "23044",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Navas",
    "nombre": "Marcelo",
    "club": "CLUB ATLETICO ADELIA MARIA",
    "id": "",
    "documento": 16474744,
    "nivel": "AFICIONADO",
    "fecha": "23336",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Carranza",
    "nombre": "Miguel",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 16831113,
    "nivel": "AFICIONADO",
    "fecha": "23484",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Salvachua",
    "nombre": "Rodolfo Raul",
    "club": "CLUB ATLETICO ADELIA MARIA",
    "id": "",
    "documento": 12554822,
    "nivel": "AFICIONADO",
    "fecha": "20774",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Wayar",
    "nombre": "Waldo",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 17000565,
    "nivel": "AFICIONADO",
    "fecha": "23574",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CATEGORIA 5",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Nicola",
    "nombre": "Estefano",
    "club": "BUCOR",
    "id": "",
    "documento": 50221340,
    "nivel": "NACIONAL",
    "fecha": "40181",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CADETE 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Aspitia",
    "nombre": "Tupac",
    "club": "CLUB UNIVERSITARIO CORDOBA",
    "id": "",
    "documento": 50628802,
    "nivel": "NACIONAL",
    "fecha": "40542",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CADETE 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Icardi",
    "nombre": "Agostina",
    "club": "sol y lago",
    "id": "",
    "documento": 49322178,
    "nivel": "NACIONAL",
    "fecha": "39870",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CADETE 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Garcia",
    "nombre": "Valentina",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 49964142,
    "nivel": "NACIONAL",
    "fecha": "40101",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "CADETE 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Caffaro",
    "nombre": "Cristiano",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 49765948,
    "nivel": "NACIONAL",
    "fecha": "40102",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "CADETE 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gauto",
    "nombre": "Alma",
    "club": "sol y lago",
    "id": "",
    "documento": 48536920,
    "nivel": "NACIONAL",
    "fecha": "39504",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "JUVENIL 1",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Juarez",
    "nombre": "Agostina",
    "club": "ATLANTIS",
    "id": "",
    "documento": 47714914,
    "nivel": "NACIONAL",
    "fecha": "39106",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "JUVENIL 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Franchello",
    "nombre": "Antonella",
    "club": "natatorio climatizado v.d",
    "id": "",
    "documento": 47319897,
    "nivel": "NACIONAL",
    "fecha": "38928",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "JUVENIL 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Etchemendi",
    "nombre": "Carolina",
    "club": "HEED",
    "id": "",
    "documento": 47665241,
    "nivel": "NACIONAL",
    "fecha": "39127",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "JUVENIL 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Moretti",
    "nombre": "Ignacio",
    "club": "Jockey Ckub Córdoba",
    "id": "",
    "documento": 46767103,
    "nivel": "NACIONAL",
    "fecha": "38814",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "JUVENIL 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Lehder",
    "nombre": "Ignacio",
    "club": "HEED",
    "id": "",
    "documento": 48068934,
    "nivel": "NACIONAL",
    "fecha": "39380",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "JUVENIL 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Valentino",
    "nombre": "Julian",
    "club": "HEED",
    "id": "",
    "documento": 48068636,
    "nivel": "NACIONAL",
    "fecha": "39347",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "JUVENIL 2",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Mayorga",
    "nombre": "Marilina",
    "club": "Velez",
    "id": "",
    "documento": 35869836,
    "nivel": "NACIONAL",
    "fecha": "33723",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "MASTER B",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Ruiz Luques",
    "nombre": "Victoria",
    "club": "ACQUAVEL",
    "id": "",
    "documento": 35581049,
    "nivel": "NACIONAL",
    "fecha": "33377",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "MASTER B",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Depetris",
    "nombre": "Noemi",
    "club": "SAN ISIDRO CLUB",
    "id": "",
    "documento": 12876767,
    "nivel": "NACIONAL",
    "fecha": "20857",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "MASTER I",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Ojeda",
    "nombre": "Eduardo",
    "club": "SAN ISIDRO CLUB",
    "id": "",
    "documento": 12560100,
    "nivel": "NACIONAL",
    "fecha": "20632",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "MASTER I",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Quiñones",
    "nombre": "Miguel",
    "club": "SAN ISIDRO CLUB",
    "id": "",
    "documento": 8340038,
    "nivel": "NACIONAL",
    "fecha": "17694",
    "genero": "MASCULINO",
    "distancia": 2250,
    "categoria": "MASTER K",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Zapata",
    "nombre": "Camila",
    "club": "HEED",
    "id": "",
    "documento": 46374940,
    "nivel": "NACIONAL",
    "fecha": "38670",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "DISTANCIA NO PERMITIDA",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Cortinez",
    "nombre": "Maria",
    "club": "HEED",
    "id": "",
    "documento": 20622717,
    "nivel": "NACIONAL",
    "fecha": "21946",
    "genero": "FEMENINO",
    "distancia": 3000,
    "categoria": "ELITE MASTER",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Luna",
    "nombre": "Paulina",
    "club": "BUCOR",
    "id": "",
    "documento": 45834860,
    "nivel": "NACIONAL",
    "fecha": "38474",
    "genero": "FEMENINO",
    "distancia": 2250,
    "categoria": "DISTANCIA NO PERMITIDA",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Daprati",
    "nombre": "Raquel",
    "club": "Club Argentino",
    "id": "",
    "documento": 12507511,
    "nivel": "NACIONAL",
    "fecha": "21506",
    "genero": "FEMENINO",
    "distancia": 3000,
    "categoria": "ELITE MASTER",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Stantero",
    "nombre": "Arnoldo",
    "club": "CLUB LIBERTADOR MASTER",
    "id": "",
    "documento": 11221380,
    "nivel": "NACIONAL",
    "fecha": "19641",
    "genero": "MASCULINO",
    "distancia": 3000,
    "categoria": "ELITE MASTER",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Alcantu",
    "nombre": "Gabriel",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 25471432,
    "nivel": "NACIONAL",
    "fecha": "28018",
    "genero": "MASCULINO",
    "distancia": 3000,
    "categoria": "ELITE MASTER",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Brussa    ",
    "nombre": "Javier",
    "club": "ac. nat. oscar garcia",
    "id": "",
    "documento": 23161966,
    "nivel": "NACIONAL",
    "fecha": "26864",
    "genero": "MASCULINO",
    "distancia": 3000,
    "categoria": "ELITE MASTER",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Aringoli",
    "nombre": "Mario",
    "club": "Club Argentino",
    "id": "",
    "documento": 14664563,
    "nivel": "NACIONAL",
    "fecha": "22559",
    "genero": "MASCULINO",
    "distancia": 3000,
    "categoria": "ELITE MASTER",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Peralta Porcel",
    "nombre": "Nicolas",
    "club": "BUCOR NATACION CORDOBA",
    "id": "",
    "documento": 28345385,
    "nivel": "NACIONAL",
    "fecha": "29511",
    "genero": "MASCULINO",
    "distancia": 3000,
    "categoria": "ELITE MASTER",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Rojas",
    "nombre": "Roberto",
    "club": "Velez",
    "id": "",
    "documento": 20307611,
    "nivel": "NACIONAL",
    "fecha": "25020",
    "genero": "MASCULINO",
    "distancia": 3000,
    "categoria": "ELITE MASTER",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Brezzo",
    "nombre": "Ruben",
    "club": "Club Argentino",
    "id": "",
    "documento": 21719087,
    "nivel": "NACIONAL",
    "fecha": "25869",
    "genero": "MASCULINO",
    "distancia": 3000,
    "categoria": "ELITE MASTER",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Sanches",
    "nombre": "Agustina",
    "club": "BUCOR",
    "id": "",
    "documento": 49221234,
    "nivel": "NACIONAL",
    "fecha": "40118",
    "genero": "FEMENINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Hormaeche",
    "nombre": "Sol",
    "club": "BUCOR",
    "id": "",
    "documento": 46658212,
    "nivel": "NACIONAL",
    "fecha": "36331",
    "genero": "FEMENINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gerbaudo Baro",
    "nombre": "Juana M.",
    "club": "Jockey Ckub Córdoba",
    "id": "",
    "documento": 48668614,
    "nivel": "NACIONAL",
    "fecha": "39801",
    "genero": "FEMENINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Paris",
    "nombre": "Virginia",
    "club": "CENTRO DEPORTIVO NADO",
    "id": "",
    "documento": 47466433,
    "nivel": "NACIONAL",
    "fecha": "39085",
    "genero": "FEMENINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Lopez Freites",
    "nombre": "Emiliano",
    "club": "BUCOR",
    "id": "",
    "documento": 46506999,
    "nivel": "NACIONAL",
    "fecha": "38875",
    "genero": "MASCULINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Almada",
    "nombre": "Lautaro",
    "club": "BUCOR",
    "id": "",
    "documento": 47320157,
    "nivel": "NACIONAL",
    "fecha": "38981",
    "genero": "MASCULINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Salinas",
    "nombre": "Lucas",
    "club": "BUCOR",
    "id": "",
    "documento": 46310922,
    "nivel": "NACIONAL",
    "fecha": "38546",
    "genero": "MASCULINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Avila",
    "nombre": "Nicanor",
    "club": "HEED",
    "id": "",
    "documento": 47907510,
    "nivel": "NACIONAL",
    "fecha": "39698",
    "genero": "MASCULINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Mina",
    "nombre": "Santino",
    "club": "BUCOR",
    "id": "",
    "documento": 46036598,
    "nivel": "NACIONAL",
    "fecha": "38600",
    "genero": "MASCULINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Gontero",
    "nombre": "Santino",
    "club": "BUCOR",
    "id": "",
    "documento": 47352404,
    "nivel": "NACIONAL",
    "fecha": "39497",
    "genero": "MASCULINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Rodríguez",
    "nombre": "Tomas",
    "club": " BUCOR",
    "id": "",
    "documento": 46127845,
    "nivel": "NACIONAL",
    "fecha": "38324",
    "genero": "MASCULINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Salanitro",
    "nombre": "Valentino",
    "club": "Federación Sanluiseña",
    "id": "",
    "documento": 48426694,
    "nivel": "NACIONAL",
    "fecha": "39547",
    "genero": "MASCULINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}, {
    "apellido": "Scalisi",
    "nombre": "Lucca",
    "club": "BUCOR",
    "id": "",
    "documento": 46973061,
    "nivel": "NACIONAL",
    "fecha": "38747",
    "genero": "MASCULINO",
    "distancia": 5000,
    "categoria": "ELITE NATACION",
    "tiempo": 9999999,
    "tiempoFormat": "-"
}]